// tslint:disable
/**
 * Ordinals API
 * A service that indexes Bitcoin Ordinals data and exposes it via REST API endpoints.
 *
 * OpenAPI spec version: v0.0.1
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

export * from "./api";
export * from "./configuration";
